"""面试状态机引擎。

对外仍从 ``app.services.interviewer_engine`` 导入：拆包不改调用方。
"""
from .constants import (
    ANSWER_TRUNCATE,
    ASK_BACK_TEXT,
    BA_GU_CLAMP,
    MAX_FOLLOW_UPS_PER_QUESTION,
    NON_ANSWER_MAX_SCORE,
    PROJECT_CLAMP,
    SKIP_EXACT,
    SUMMARIZING_TEXT,
    WEAK_KEYWORDS,
)
from .engine import InterviewEngine
from .guards import (
    _char_overlap_ratio,
    _conflicts_avoid,
    _conflicts_bagu_knowledge,
    _conflicts_historical_question,
    _conflicts_plan_sibling,
    _has_ngram_overlap,
    _is_failed_coding_submit,
    _is_repeat_followup,
    _is_similar_question,
    _is_suspect_pure_backend_project_blob,
    _is_thin_answer,
    _looks_like_vague_orchestration,
    _norm_text,
    _question_mentions_project,
    _topic_key_tags,
    filter_strengths,
    is_non_answer,
    looks_like_rubric,
    sanitize_score_fields,
)

__all__ = [
    "ANSWER_TRUNCATE",
    "ASK_BACK_TEXT",
    "BA_GU_CLAMP",
    "InterviewEngine",
    "MAX_FOLLOW_UPS_PER_QUESTION",
    "NON_ANSWER_MAX_SCORE",
    "PROJECT_CLAMP",
    "SKIP_EXACT",
    "SUMMARIZING_TEXT",
    "WEAK_KEYWORDS",
    "_char_overlap_ratio",
    "_conflicts_avoid",
    "_conflicts_bagu_knowledge",
    "_conflicts_historical_question",
    "_conflicts_plan_sibling",
    "_has_ngram_overlap",
    "_is_failed_coding_submit",
    "_is_repeat_followup",
    "_is_similar_question",
    "_is_suspect_pure_backend_project_blob",
    "_is_thin_answer",
    "_looks_like_vague_orchestration",
    "_norm_text",
    "_question_mentions_project",
    "_topic_key_tags",
    "filter_strengths",
    "is_non_answer",
    "looks_like_rubric",
    "sanitize_score_fields",
]
